### PR TITLE
Fix _setupInternalEventBindings() in 1.1.0

### PR DESCRIPTION
**Pull request by martinfilliau**
Fixes the latest release on NPM (1.1.0) and the unit tests are passing again.

### CODE REVIEW

**Comment by michaelenger** [comment]
Didn't understand why my friend was having a problem with the app while mine was fine. Good catch 👍

**Comment by epenetar** [comment]
Yes, please merge! After update, app was failing, and took a while to figure out why.

**Comment by nathanbuchar** [comment]
Whoopsie daisy. Thank you!

**Comment by martinfilliau** [comment]
Thanks for merging!

Would be great if the releases could be tagged on GitHub, as far as I can see the `master` branch is still at `1.1.0` whereas `1.1.1` has been published on npm... Also, may I suggest to enable the Travis-CI integration so that, in the future, unit tests are running automatically for every pull request?

**Comment by nathanbuchar** [comment]
Yessir! I'm working on a 2.0 version as we speak and will be integrating Travis for automatic testing. This package has suddenly picked up some speed so I'm trying to meet expectations and simplify/refactor a lot of it.

I'll look into properly tagging

**Pull request merged**
