### PR TITLE
Replace `write-file-atomic` with `atomically`

### LINKED ISSUE #159: EPERM in windows, rename settings.json.2058848393 to settings.json
Seems similar to https://github.com/nathanbuchar/electron-settings/issues/55

```json
{"code":"EPERM","dest":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json","errno":-4048,"level":"error","path":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json.3730721750","syscall":"rename","timestamp":"2021-10-26T01:04:40.886Z"}
{"code":"EPERM","dest":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json","errno":-4048,"level":"error","path":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json.2058848393","syscall":"rename","timestamp":"2021-10-26T01:12:03.256Z"}
{"code":"EPERM","dest":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json","errno":-4048,"level":"error","path":"C:\\Users\\lambda\\AppData\\Roaming\\TiddlyGit\\settings\\settings.json.44303103","syscall":"rename","timestamp":"2021-10-26T01:12:20.745Z"}
```

Maybe caused by write-file-atomic package.

### LINKED ISSUE #169: windows `operation not permitted, rename ...`
Recently, when I opened my electron-application and the program ran to store the local custom data logic, the following error was reported.( I used `electron-settings` to store)

` Error: EPERM: operation not permitted, rename 'C:\Users\yujingxiacai\AppData\Roaming\Electron\settings.json.2501025886' -> 'C:\Users\yujingxiacai\AppData\Roaming\Electron\settings.json'`

> - **Opreating System**:    Windows 10 pro（21H2）
> - **Electron Version**:  ^15.1.0
> - **electron-settings**:  ^4.0.2

### PR DESCRIPTION
**Pull request by quanglam2807**
Resolve #159 
Resolve #169 

CC: @nathanbuchar

Reference: https://github.com/sindresorhus/electron-store/issues/103

### CODE REVIEW

**Comment by nathanbuchar** [comment]
Thank you!

**Comment by nathanbuchar** [comment]
I'll deploy this tonight.

**Comment by quanglam2807** [comment]
Thanks so much, @nathanbuchar. For releasing, you'll probably need to modify `src/settings.ts` to drop `remote` support.  

You can check out my fork for referencing: https://github.com/webcatalog/electron-settings/commit/9db71fdb4ef784d73319e1ff120af2d8508e6ae1#diff-bb57a3bd912abc3ec2e729cb8a743838487677a5517683d0c8913a3619ac296a

If possible, I'd love to join as a maintainer of this project.

**Comment by nathanbuchar** [comment]
@quanglam2807 sorry, didn't get around to it tonight. I'd be happy to add you as a maintainer, as I haven't used Electron in years. if you get this fully ready, I'll publish a new version.

**Comment by nathanbuchar** [comment]
I sent the Github collaborator invite over to you last night, but I see it's still marked as pending.

**Comment by quanglam2807** [comment]
@nathanbuchar Thank you! It's ready for release now.

**Comment by nathanbuchar** [comment]
Excellent. Many thanks for your help and your agency for keeping this repository properly maintained. I have just published v5.0.0 to npm (`@latest`). Please install the latest version and make sure everything was properly published and working as expected.

For future reference, I run `npm run release` to automatically boost the version number and update the changelog, so as long as you use the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec correctly, the release script will automatically boost to the proper semantic version without needing to modify the package.json manually.

I don't suppose the tests are working with your most recent changes? I wasn't able to test things locally, but I don't currently have Electron installed. Would be good to have tests functional in some sort of CI (I was using Travis before) as a sanity test for future PRs.

Thanks again!

**Comment by jabdinghoff** [comment]
What exactly happened to the 5.0.0 release and this merge?

**Comment by nathanbuchar** [comment]
This released, but immediately introduced #178, so I rolled back. I am not really actively maintaining this, and @quanglam2807 disappeared after pushing this so I wasn't able to get his help. Open to (stable) PRs :)

**Pull request merged**
